"""empty message

Revision ID: 50c4f75bee05
Revises: f7f15c29f010
Create Date: 2017-01-31 23:48:54.434502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c4f75bee05'
down_revision = 'f7f15c29f010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('cred_at', sa.DateTime(), nullable=True),
    sa.Column('author_uid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['author_uid'], ['Account.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Post_cred_at'), 'Post', ['cred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Post_cred_at'), table_name='Post')
    op.drop_table('Post')
    # ### end Alembic commands ###
