"""empty message

Revision ID: cf6c6d1681f3
Revises: 50c4f75bee05
Create Date: 2017-03-12 11:00:30.634221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6c6d1681f3'
down_revision = '50c4f75bee05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'body_html')
    # ### end Alembic commands ###
