"""empty message

Revision ID: f7f15c29f010
Revises: 3b63b713160f
Create Date: 2017-01-31 16:45:09.823884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f15c29f010'
down_revision = '3b63b713160f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserInfo', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserInfo', 'avatar_hash')
    # ### end Alembic commands ###
